server:
  #context-path: /gril 访问项目前缀
  port: 8080
#配置文件前面不能有空格(一个缩进tab)，否则获取数据需要${server.cupSize}格式，而不是${cupSize}
cupSize: B   #controler接受时再给数据类型。
age: 18 #controler接受时再给数据类型。string int 等等
test: 中文 #controler接受时再给数据类型。直接中文也行
  #配置里面使用配置,记得每个冒号后面加空格
content: "cupSize: ${cupSize},test: ${test}"
girl:
  age: 25
  cupSize: B